version: '3.0'
services:
  web:
    container_name: web
    image: alexcheng/magento2
    ports:
      - "9090:80"
    links:
      - db
    env_file:
      - env
    environment:
      MAGENTO_URL: http://f02fc6d3.ngrok.io
  db:
    image: mysql:5.6.23
    env_file:
      - env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db